const weekWords = [
['JXVCQ','JWSCM','DHGCD','FPRKW','TXQWQ','FFDTU','ERLTQ','JXOCG','WIIRP','SSOGT','XMQWN','JCDVF','YYXTC','YLFKM','FQRTB','NZRWN','THOCC','NPJKD','RIKEB','THQWN','TLOCH','WMVQD','YYEOF','TWHTQ'],
['DLVKG','YYRRT','JDLTQ','FKRTE','FXQQN','SSOCT','FVRNG','WEQKE','JXNGT','JQUKG','WMDJD','YRDOB','WIJCN','CIGPJ','UPXVT','TKQCG','TGOCG','FJQKO','FVLQM','XIFQE','XEUVB','RMWNV','XYWDP','JFPQS'],
['YWUKG','MXOKG','DXRQT','FXVKW','FMUQO','JZDNM','WIOCU','JJXVT','NIEPB','SSVKC','WIWQE','JQLTG','YWUQW','UIRTH','SINGU','TIVWN','FVEOP','JLJQE','QEXIJ','WEOGT','WELHB','WIQKN','JQWKS','WEGWN'],
['IRHKG','WSVKW','IPLWC','SSECK','FXHQQ','TRHWC','TVNKN','JXVCQ','WSYQX','JQLDB','JRLJD','XRHKT','IRDTC','YLFCW','FQPQL','JVDUP','FKQWM','FSQCD','FXLTG','FKHJD','WIWGS','IMXNG','FMQVF','JMUGT'],
['QADTC','JVRFB','YYRDB','WEVGQ','XYWEJ','QEÇWQ','WSYGC','WSSOF','JXUGH','WILEB','JYOCW','JRDNQ','WIFCS','JNNCW','YLFKE','TVEKM','FQUKG','TRQCT','THXIB','TTPGU','XSWCQ','FVEOP','JDOQQ','TMFRP'],
['YSJKC','MGUQQ','JWUWQ','TKHKS','TLFGU','FFPWU','WINPB','ERDNH','JDWCL','XIGKB','JPRTG','XIXQW','QIJGL','SISQI','UPDET','NEVGQ','TVWGW','TXQGT','TZUGT','TQLBB','XEIQG','NFUGE','FVEQQ','FVGGQ'],
['DXVWH','MGXQW','DVUGG','FXQGN','TLFKC','TMFQS','THOCT','JPKQE','JXRHQ','JVLQG','JWUWP','SSSCK','SIJGO','JMOCN','XIFDB','TPXOF','FHLOV','TMSOB','SIPKI','FLFGN','XSJCC','YEFGQ','JVXQN','SSJGT']
];

const weekDates = ['10-4-2022','11-4-2022','5-4-2022','6-4-2022','7-4-2022','8-4-2022','9-4-2022'];