const weekWords = [

['JXLTX','YEHTH','PGRND','FWLTC','FFPWS','WEOGQ','EMWQO','LMQGX','YOUCN','SSOGN','YSSOJ','XEHNB','YLFCA','QIIQK','XIRNC','NLJQW','FHQGC','FWUQC','WMWCM','WEWQC','FWOCC','WYJGT','WSFKM','TVUCT'],
['YRXQN','YTBTD','QIEGS','WMQGW','WEPKU','FHQQS','SSWGC','JJXCU','JXWKT','WYHNG','JGUCG','YRDWT','JHQKX','JMQCN','QIROT','TGLCM','NEJGM','JVGCQ','TKVWN','QMYQD','WEECH','WEOQE','FKRTE','QELGS'],
['JVLRT','UQLMT','JZDJT','TKVCS','FQUKG','QIGCQ','PEEQU','YYDTC','JOUCI','WIACU','JWRTQ','JPECD','JXOKL','JAUCU','XOQKM','TXVCC','NLFWC','FFPCH','XSUCD','FXVQD','TZUGD','JVIQH','FXVKW','XSAWM'],
['JKGCC','YTHPJ','JXDTD','JWDND','JVIQH','XEUVB','SIGCC','JXQCL','WEJQT','KMWCO','JGQQG','XIFQO','RVHYA','YWUGH','SISCS','FTVKW','NGUGC','TKHNT','TLQKQ','RYENB','THLCT','FGQKG','TVWGN','TVXCU'],
['LRLJU','JXLWR','WIQKM','SSWCN','TVHVV','WEJCW','QIGCO','YMPGT','PMUAM','JYJCE','XRHKU','JQPQQ','YLFCX','JNWKQ','QSRFJ','TGOCQ','TXHPB','TGFCQ','WIECT','WISWT','XEGQN','WEPWT','QSVGQ','FZLNP'],
['DVWPF','MWXTD','QVDPT','FQHQQ','FVRNG','WIFQD','JMWMB','SMUQX','JDWKI','XYUKW','JGDNH','XMDTW','SINCI','JMUQQ','JWUQN','JPLOV','FHUQD','TWXHT','XYQQC','TRLWT','EMUVB','TMGCS','WEVGQ','WEJGO'],
['JHXTD','JQLTH','JWRQH','QMFQE','WIECI','QEWGN','QEQKG','CIGQD','JPLGA','XRLCC','LRLQQ','SEEWS','YICOP','TVWGN','TMWCQ','NLJCM','FGRRF','TMGFB','TGLCM','TRHNQ','JVEQE','FTVGW','TGOCC','FPUWC'],
['HMGGN','TFUWU','HMQWU','WEOGU','REOUJ','WSYCG','JHQKC','WIEWA','JQXNC','JQUCM','JHQQN','WMOCT','QIICS','WEQQT','SSRTL','NRDTD','TYJGT','TXVQN','TPHRB','TFUWU','FLOCQ','TMPCD','FWUWD','TVUCD'],
['YGLXF','IPXQX','PRDJT','FXQGS','TKHWM','JMUGT','LMVOF','WIXCC','IQHTG','JRJKT','JQOCQ','SSBCS','YSSGE','WICQH','WIGCE','FWXNC','FVWKN','JTUGT','THLOB','FXQKD','TDLWK','XIQKY','JPEQO','XSXSB'],
['XYQQC','YWDGC','JZOCT','WSPWU','TGLVF','QMECI','PRDTU','QLDVT','QIIRB','YMECI','JQJQE','WMUGQ','NIURT','SIUCH','FQHJU','FQUQG','FMQGU','TVUGD','FXVGC','FQLGU','FSUQD','FÑUQG','TBQCH','FRXCG'],
['RVDYT','DXIGI','MGDGU','SSJCW','FZHWO','XIQWM','JKRTE','PMJQM','SIVUF','JHBZP','TMGCS','YYRLB','JFPQU','YJLTE','WIWCM','FVHRT','TMUVB','FWVCU','XMDGS','FXOGD','JHXÑB','ÑMOGG','TCQKQ','NXDNM'],
['WIKVP','YWLQI','YMFCU','FXQKD','WMFGE','FOGQW','PVDVT','SIVQU','SYPOJ','JWLTG','YRLQK','TNQCC','SSGKC','XPLCS','BYHGH','TXLFV','TIUWB','NEGWT','XEPQH','FXHKE','FXVGU','JKWCQ','NRPQT','YPXEP'],
['JVRJT','PGLTU','DZDTH','TGQCN','QSUCG','QIYKO','YJQCT','LMQQI','KTPCE','ZFLTU','YSJTB','XSDJD','JHQQT','QICLJ','QEDVT','NXOQN','NEWQO','NHUQC','XIGQC','TXUCQ','EMWCN','FQUQO','FPSGS','WEOQW'],
['JRLJT','DOVGQ','FVWZF','WEWQW','XSQGN','TRDKQ','MGHNC','GEQKI','JRKCG','JLFTB','ZHQGQ','SMQGC','LRDNT','JNWQS','IMXTC','NPJQU','THDWH','JKJQS','NIOQW','JVJKU','WEUKN','FCQKW','ÑEQGU','YMUCN'],
['MXDGE','IRXQT','WEGGD','FQHTD','TZHWI','EEGWB','GEUGI','YWLGN','YLFWX','JVLQC','WIOQW','IMRTG','SNLBB','PNLNP','YLFQW','JVLIB','FHLWH','FPUGQ','XELQC','TXHTQ','TEUCG','FVWZF','WEOGU','WEOQD'],
['TXVGQ','DPZGO','SSUGI','WEGGT','FQLTH','TIGQS','FQJQE','RYUCX','IRRNC','JPDTP','XSSGS','SEWPB','JNJWN','YSQGH','WIYGL','FGVKM','TJXVT','NEOGD','XTLND','XMSCM','WEUKW','JPFPP','TRDKQ','WMDTU'],
['JTLTH','SADTQ','QPHYT','WSÇGT','WEJWK','QEYKS','JWLTL','QEUQN','KJLTH','JWXCQ','NSUCQ','JPJPB','ISJHB','YNLRT','RICGC','TTVGD','JGQKM','FZRET','TZOCT','TVWKD','FLFQN','FXQKQ','JVSUB','JVJQT']
];

const weekDates = ['29-4-2022','30-4-2022','1-5-2022','2-5-2022','3-5-2022','4-5-2022','5-5-2022','6-5-2022','7-5-2022','8-5-2022','9-5-2022','10-5-2022','11-5-2022','12-5-2022','13-5-2022','14-5-2022','15-5-2022'];