const weekWords = [
['YRDNT','SMDTU','JOLRT','WIJQD','FQXGS','FRDKE','SMOQQ','MGOKN','JYHTU','WMEWT','JYTKC','WMQKG','XYWQM','SMXTC','JMWRP','TWXKS','NEJGO','JLFWO','XSAKG','JXUQQ','XEQWE','TFUCD','HMWRP','TKQCN'],
['JPECU','JGDRT','DKJCC','XMWWD','TWHKU','FGCKQ','XLFWG','LMOFB','SIAQC','ZZHTQ','YRROB','JIKVB','JQDTG','YWUQX','QNLVT','NGOGT','NHDVT','TGUWU','FLQKN','FXOQW','WEXVB','FPJPV','FPFGU','JVIQD'],
['JKUWQ','PGRTG','JWDDB','JZDND','SYJNB','XSEOB','NIEQX','QENQW','NIWDB','JLFCM','YIOQW','JXDRF','LMQGN','PGDPT','UIRTU','TXXKB','FXQGN','FKLTC','FLFWC','FKOGD','XELWD','YMUGG','NYTUF','XIJCQ'],
['YVXNC','DPSGS','JTHTD','TVWKM','WEPKM','WEWQO','SVHVT','JPKQL','IVRLG','YIFCM','IVRDB','XGLCM','WMNCG','XMXTL','SINGX','FWQGN','NEEWS','TKRHT','WSPWI','TEIWU','WMYWP','JBWQD','FXQWK','QEECD'],
['PEHPT','YJDJT','YIHJT','FRUQT','TXQCT','JZHWO','QEPWA','WIKQX','YYOCT','JMUWG','JVWKM','XILPV','YLFCO','YLFKK','WIMPB','TXVGS','NFPCD','TXWGO','TGLRF','WISKA','TÑDTC','FHUQD','XIWCN','NFPQA'],
['WIICX','TXVWH','DHGWN','TIOCK','THDGN','TMWKM','WYJKG','SIWCS','TMGCS','JLFCW','WISWE','JQDNC','BYDNG','PRDNT','DTSWH','JLJWS','TGXTC','FMEDB','JTVCK','FXVGD','WICCG','JXPQD','JRJKT','YSEQS'],
['LRDYU','JDLCN','CIQPB','THUCO','THLWS','WSECM','SIGTP','QINPP','YLFCQ','JXLIB','JWLXB','NQUCQ','RYUGT','YIGCL','WECKC','FMJGS','TGHTH','FXVCD','WIPQD','TGHTU','FLOQS','LIWCC','WIOQW','YYOGQ'],
['RIUCI','YWLQG','DVLCG','FDHKQ','TWXDB','JLFQD','QILRT','YJDTL','WIGGG','WIVCD','ZEBQC','JVLCN','NIRPL','YLFCQ','YISKQ','TKQCS','FIQKM','THXET','FZXJD','FGRTU','FWRTQ','WESQE','WEFQU','WEUTF'],
['LMURT','YYEGE','MGLJX','WMPGH','TTXTH','TGUGU','SYDTC','SEJTP','JPOGA','RYUQG','XIJWK','WIWCH','QYSOB','UQDNL','WEDVT','FRREJ','FKHOP','NEYQD','THUWT','FXLGT','TEYQQ','FMSQD','IMOCW','FXQCN'],
['YRDGN','QIYCH','JKGWC','WEJGQ','TXLTH','XILTB','WINQQ','QIEQI','JQOCQ','XXQGM','XVHJD','WECCC','RYENB','SMGQK','RPDUQ','NZDUV','NHUCU','FQOGN','TEVWG','JPEWE','TMHTG','QSWGS','WMOGE','TÑQCD'],
['WINCC','JYJTB','UEUVT','FKOWQ','WEOGI','FHQCC','SMETF','SIEQM','JWLGN','XIGWS','TZDTC','SSLPV','SIRKQ','WIYLJ','WINOJ','FQXKQ','JTRKN','JVROB','TKOWW','FZXQM','FXQQN','HRRTU','RYOQW','WEGCO'],
['JXLTX','YEHTH','PGRND','FWLTC','FFPWS','WEOGQ','EMWQO','LMQGX','YOUCN','SSOGN','YSSOJ','XEHNB','YLFCA','QIIQK','XIRNC','NLJQW','FHQGC','FWUQC','WMWCM','WEWQC','FWOCC','WYJGT','WSFKM','TVUCT'],
['YRXQN','YTBTD','QIEGS','WMQGW','WEPKU','FHQQS','SSWGC','JJXCU','JXWKT','WYHNG','JGUCG','YRDWT','JHQKX','JMQCN','QIROT','TGLCM','NEJGM','JVGCQ','TKVWN','QMYQD','WEECH','WEOQE','FKRTE','QELGS']
];

const weekDates = ['18-4-2022','19-4-2022','20-4-2022','21-4-2022','22-4-2022','23-4-2022','24-4-2022','25-4-2022','26-4-2022','27-4-2022','28-4-2022','29-4-2022','30-4-2022'];